version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    expose:
      - "80"
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:5.8.3
    container_name: artifactory
    expose:
      - 8081
    ports:
      - 8081
    volumes:
      - /data/artifactory:/var/opt/jfrog/artifactory
    environment:
      - VIRTUAL_HOST=artifactory.local
    extra_hosts:
      - "gitlab.local:192.168.102.64"
      - "jenkins.local:192.168.102.64"
      - "artifactory.local:192.168.102.64"
      - "registry.local:192.168.102.64"
      - "jaeger.local:192.168.102.64"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    expose:
      - 8080
    ports:
      - 8080
      - 50000:50000
    volumes:
      - /data/jenkins:/var/jenkins_home
    environment:
      - VIRTUAL_HOST=jenkins.local
      - VIRTUAL_PORT=8080
    extra_hosts:
      - "gitlab.local:192.168.102.64"
      - "jenkins.local:192.168.102.64"
      - "artifactory.local:192.168.102.64"
      - "registry.local:192.168.102.64"
      - "jaeger.local:192.168.102.64"
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    hostname: 'gitlab.local'
    environment:
      VIRTUAL_HOST: gitlab.local
      VIRTUAL_PORT: 80
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.local'
        # Add any other gitlab.rb configuration here, each on its own line
    extra_hosts:
      - "gitlab.local:192.168.102.64"
      - "jenkins.local:192.168.102.64"
      - "artifactory.local:192.168.102.64"
      - "registry.local:192.168.102.64"
      - "jaeger.local:192.168.102.64"
    volumes:
      - '/data/gitlab/config:/etc/gitlab'
      - '/data/gitlab/logs:/var/log/gitlab'
      - '/data/gitlab/data:/var/opt/gitlab'
    restart: always
  docker-registry:
    image: 'registry:2'
    container_name: docker-registry
    environment:
      VIRTUAL_HOST: registry.local
      VIRTUAL_PORT: 5000
    extra_hosts:
      - "gitlab.local:192.168.102.64"
      - "jenkins.local:192.168.102.64"
      - "artifactory.local:192.168.102.64"
      - "registry.local:192.168.102.64"
      - "jaeger.local:192.168.102.64"
    volumes:
      - '/data/registry:/var/lib/registry'
      - './etc/docker/registry/config.yml:/etc/docker/registry/config.yml'
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - VIRTUAL_HOST=jaeger.local
      - VIRTUAL_PORT=16686
    extra_hosts:
      - "gitlab.local:192.168.102.64"
      - "jenkins.local:192.168.102.64"
      - "artifactory.local:192.168.102.64"
      - "registry.local:192.168.102.64"
      - "jaeger.local:192.168.102.64"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    environment:
      - VIRTUAL_HOST=prometheus.local
      - VIRTUAL_PORT=9090
    extra_hosts:
      - "gitlab.local:192.168.102.64"
      - "jenkins.local:192.168.102.64"
      - "artifactory.local:192.168.102.64"
      - "registry.local:192.168.102.64"
      - "jaeger.local:192.168.102.64"
